-- drop tables
drop table hd_user cascade constraints;
drop table hd_request cascade constraints;
drop table hd_attachment cascade constraints;
drop table hd_ticket cascade constraints;
drop table hd_client_feedback cascade constraints;
drop table hd_ticket_comm cascade constraints;
drop table hd_support_team cascade constraints;
drop table hd_task cascade constraints;
drop table hd_task_assignment cascade constraints;
drop table hd_visit_schedule cascade constraints;
drop table hd_lookup cascade constraints;

-- create tables
create table hd_lookup (
    id                             number generated by default on null as identity 
                                   constraint hd_lookup_id_pk primary key,
    lookup_type                    varchar2(255 char),
    lookup_code                    varchar2(255 char),
    lookup_value                   varchar2(4000 char),
    lookup_desc                    varchar2(4000 char),
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

create table hd_user (
    id                     number generated by default on null as identity 
                                   constraint hd_user_id_pk primary key,
    username                       varchar2(255 char) not null,
    password                       varchar2(4000 char),
    email                          varchar2(255 char),
    user_type                      varchar2(255 char),
    profil_url                     varchar2(255 char),
    active_flag                    varchar2(1),
    tenant                         clob check (tenant is json),
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

create table hd_request (
    id                  number generated by default on null as identity 
                                   constraint hd_request_id_pk primary key,
    user_id                        number
                                   constraint hd_request_user_id_fk
                                   references hd_user on delete cascade,
    request                        varchar2(4000 char) not null,
    submitted_date                 date,
    feature                        clob check (feature is json),
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index hd_request_i1 on hd_request (user_id);

create table hd_attachment (
    id               number generated by default on null as identity 
                                   constraint hd_attachment_id_pk primary key,
    parent_id                      number,
    parent_source_type             varchar2(255 char),
    filename                       varchar2(4000 char),
    fileurl                        varchar2(4000 char),
    filepath                       varchar2(4000 char),
    status                         number,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

create table hd_ticket (
    id                   number generated by default on null as identity 
                                   constraint hd_ticket_id_pk primary key,
    request_id                     number
                                   constraint hd_ticket_request_id_fk
                                   references hd_request on delete cascade,
    ticket_number                  varchar2(255 char),
    feature                        varchar2(4000 char),
    category                       number,
    type                           number,
    impact                         number,
    urgency                        number,
    closing_status                 varchar2(1),
    closing_date                   date,
    closing_remark                 varchar2(4000 char),
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index hd_ticket_i1 on hd_ticket (request_id);

create table hd_client_feedback (
    id          number generated by default on null as identity 
                                   constraint hd_client_feedback_id_pk primary key,
    user_id                        number
                                   constraint hd_client_feedback_user_id_fk
                                   references hd_user on delete cascade,
    ticket_id                      number
                                   constraint hd_client_feedback_ticket_i_fk
                                   references hd_ticket on delete cascade,
    feedback                       varchar2(4000 char),
    rating                         number,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index hd_client_feedback_i1 on hd_client_feedback (ticket_id);
create index hd_client_feedback_i122 on hd_client_feedback (user_id);

create table hd_ticket_comm (
    id              number generated by default on null as identity 
                                   constraint hd_ticket_comm_id_pk primary key,
    ticket_id                      number
                                   constraint hd_ticket_comm_ticket_id_fk
                                   references hd_ticket on delete cascade,
    sender_id                      number,
    sender_source_type             varchar2(255 char),
    content                        varchar2(4000 char),
    reply_to                       number
                                   constraint hd_ticket_comm_reply_to_fk
                                   references hd_ticket_comm on delete cascade,
    status                         number,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index hd_ticket_comm_i1 on hd_ticket_comm (reply_to);
create index hd_ticket_comm_i172 on hd_ticket_comm (ticket_id);

create table hd_support_team (
    id             number generated by default on null as identity 
                                   constraint hd_support_team_id_pk primary key,
    user_id                        number
                                   constraint hd_support_team_user_id_fk
                                   references hd_user on delete cascade,
    position                       number,
    name                           varchar2(4000 char),
    active_flag                    varchar2(1),
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index hd_support_team_i1 on hd_support_team (user_id);

create table hd_task (
    id                     number generated by default on null as identity 
                                   constraint hd_task_id_pk primary key,
    ticket_id                      number
                                   constraint hd_task_ticket_id_fk
                                   references hd_ticket on delete cascade,
    task_name                      varchar2(255 char),
    approval_status                number,
    approval_date                  date,
    approval_by                    number
                                   constraint hd_task_approval_by_fk
                                   references hd_support_team on delete cascade,
    completion_status              number,
    completion_time                date,
    completion_remark              varchar2(4000 char),
    completion_update_by           number
                                   constraint hd_task_completion_update_b_fk
                                   references hd_support_team on delete cascade,
    priority                       number,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index hd_task_i1 on hd_task (approval_by);
create index hd_task_i262 on hd_task (completion_update_by);
create index hd_task_i273 on hd_task (ticket_id);

create table hd_task_assignment (
    id          number generated by default on null as identity 
                                   constraint hd_task_assignment_id_pk primary key,
    task_id                        number
                                   constraint hd_task_assignment_task_id_fk
                                   references hd_task on delete cascade,
    assignee                       number
                                   constraint hd_task_assignment_assignee_fk
                                   references hd_support_team on delete cascade,
    is_task_owner                  varchar2(1),
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index hd_task_assignment_i1 on hd_task_assignment (assignee);
create index hd_task_assignment_i322 on hd_task_assignment (task_id);

create table hd_visit_schedule (
    id           number generated by default on null as identity 
                                   constraint hd_visit_schedule_id_pk primary key,
    task_id                        number
                                   constraint hd_visit_schedule_task_id_fk
                                   references hd_task on delete cascade,
    visit_start                    date,
    visit_end                      date,
    approval_status                number,
    approval_date                  date,
    approval_by                    number
                                   constraint hd_visit_schedu_approval_by_fk
                                   references hd_support_team on delete cascade,
    visit_status                   number,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index hd_visit_schedule_i1 on hd_visit_schedule (approval_by);
create index hd_visit_schedule_i372 on hd_visit_schedule (task_id);


-- triggers
create or replace trigger hd_lookup_biu
    before insert or update 
    on hd_lookup
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end hd_lookup_biu;
/

create or replace trigger hd_user_biu
    before insert or update 
    on hd_user
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end hd_user_biu;
/

create or replace trigger hd_request_biu
    before insert or update 
    on hd_request
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end hd_request_biu;
/

create or replace trigger hd_attachment_biu
    before insert or update 
    on hd_attachment
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end hd_attachment_biu;
/

create or replace trigger hd_ticket_biu
    before insert or update 
    on hd_ticket
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end hd_ticket_biu;
/

create or replace trigger hd_client_feedback_biu
    before insert or update 
    on hd_client_feedback
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end hd_client_feedback_biu;
/

create or replace trigger hd_ticket_comm_biu
    before insert or update 
    on hd_ticket_comm
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end hd_ticket_comm_biu;
/

create or replace trigger hd_support_team_biu
    before insert or update 
    on hd_support_team
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end hd_support_team_biu;
/

create or replace trigger hd_task_biu
    before insert or update 
    on hd_task
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end hd_task_biu;
/

create or replace trigger hd_task_assignment_biu
    before insert or update 
    on hd_task_assignment
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end hd_task_assignment_biu;
/

create or replace trigger hd_visit_schedule_biu
    before insert or update 
    on hd_visit_schedule
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end hd_visit_schedule_biu;
/

-- load data
 
-- Generated by Quick SQL Wednesday November 02, 2022  11:13:19
 
/*
hd_user
 id /pk
 username vc255 /nn
 password vc32k
 email vc255
 user_type vc255
 active_flag num
 tenant json

hd_request
 id /pk
 user_id /reference hd_user
 request vc32k /nn
 submitted_date date
 feature json

hd_attachment
 id /pk
 parent_id num
 parent_source_type vc255
 filename vc32k
 fileurl vc32k
 filepath vc32k
 status num

hd_ticket
 id /pk
 request_id /reference hd_request
 ticket_number vc255
 feature json
 category num
 type num
 impact num
 urgency num
 closing_status num
 closing_date date
 closing_remark vc32k

hd_client_feedback
 id /pk
 user_id /reference hd_user
 ticket_id /reference hd_ticket
 feedback vc32k
 rating num

hd_ticket_comm
 id /pk
 ticket_id /reference hd_ticket
 sender_id num
 sender_source_type vc255
 content vc32k
 reply_to num /reference hd_ticket_comm
 status num

hd_support_team
 id /pk
 user_id /reference hd_user
 position num
 name vc32k
 active_flag num

hd_task
 id /pk
 ticket_id /reference hd_ticket
 task_name vc255
 approval_status num
 approval_date date
 approval_by /reference hd_support_team
 completion_status num
 completion_time date
 completion_remark vc32k
 completion_update_by /reference hd_support_team

hd_task_assignment
 id /pk
 task_id /reference hd_task
 assignee /reference hd_support_team

hd_visit_schedule
 id /pk
 task_id /reference hd_task
 visit_start date
 visit_end date
 approval_status num
 approval_status num
 approval_date date
 approval_by /reference hd_support_team
 visit_status num

# settings = { semantics: "CHAR", auditCols: true, language: "EN", APEX: true, prefixPKwithTname: true }
*/
